INSERT INTO airline(id, name, type) values( 1000, 'KLM'); 
INSERT INTO airline(id, name, type) values( 1100, 'American Airlines'); 
INSERT INTO airline(id, name, type) values( 1200, 'Air Belgium'); 
INSERT INTO airline(id, name, type) values( 1300, 'ASL Airlines Belgium'); 
INSERT INTO airline(id, name, type) values( 1400, 'Brussels Airlines N.V.'); 
INSERT INTO airline(id, name, type) values( 1500, 'TUI Airlines Belgium NV'); 
INSERT INTO airline(id, name, type) values( 1600, 'VLM Airlines N.V.'); 
INSERT INTO airline(id, name, type) values( 1700, 'Air Hollandia B.V.'); 
INSERT INTO airline(id, name, type) values( 1800, 'Airshop B.V.'); 
INSERT INTO airline(id, name, type) values( 1900, 'KLM'); 
INSERT INTO airline(id, name, type) values( 2000, 'American Airlines'); 
INSERT INTO airline(id, name, type) values( 2100, 'Air Belgium'); 
INSERT INTO airline(id, name, type) values( 2200, 'ASL Airlines Belgium'); 
INSERT INTO airline(id, name, type) values( 2300, 'Brussels Airlines N.V.'); 
INSERT INTO airline(id, name, type) values( 2400, 'TUI Airlines Belgium NV'); 
INSERT INTO airline(id, name, type) values( 2500, 'VLM Airlines N.V.'); 
INSERT INTO airline(id, name, type) values( 2600, 'Air Hollandia B.V.'); 
INSERT INTO airline(id, name, type) values( 2700, 'Airshop B.V.'); 

INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(100, 'A318', 300, 55, 'Airbus 319', 1);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(200, 'A318', 300, 55, 'Airbus 319', 1);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(300, 'A318', 300, 55, 'Airbus 319', 2);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(400, 'A321', 250, 50, 'Airbus A321-100/200', 2);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(500, 'A330', 290, 55, 'Airbus A330 ', 2);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(600, 'A318', 300, 55, 'Airbus 319', 2);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(700, 'A318', 300, 55, 'Airbus 319', 2);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(800, 'A318', 300, 55, 'Airbus 319', 3);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(900, 'A318', 300, 55, 'Airbus 319', 4);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(1000, 'A321', 250, 50, 'Airbus A321-100/200', 3);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(1100, 'A330', 290, 55, 'Airbus A330 ', 2);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(1200, 'A318', 300, 55, 'Airbus 319', 5);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(1300, 'A318', 300, 55, 'Airbus 319', 6);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(1400, 'A318', 300, 55, 'Airbus 319', 5);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(1500, 'A318', 300, 55, 'Airbus 319', 1);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(1600, 'A318', 300, 55, 'Airbus 319', 1);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(1700, 'A318', 300, 55, 'Airbus 319', 1);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(1800, 'A318', 300, 55, 'Airbus 319', 2);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(1900, 'A321', 250, 50, 'Airbus A321-100/200', 2);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(2000, 'A330', 290, 55, 'Airbus A330 ', 2);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(2100, 'A318', 300, 55, 'Airbus 319', 2);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(2200, 'A318', 300, 55, 'Airbus 319', 2);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(2300, 'A318', 300, 55, 'Airbus 319', 3);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(2400, 'A318', 300, 55, 'Airbus 319', 4);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(2500, 'A321', 250, 50, 'Airbus A321-100/200', 3);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(2600, 'A330', 290, 55, 'Airbus A330 ', 2);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(2700, 'A318', 300, 55, 'Airbus 319', 5);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(2800, 'A318', 300, 55, 'Airbus 319', 6);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(2900, 'A318', 300, 55, 'Airbus 320', 5);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(3000, 'A318', 300, 55, 'Airbus 321', 1);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(3100, 'A318', 300, 55, 'Airbus 322', 9);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(3200, 'A318', 300, 55, 'Airbus 323', 8);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(3300, 'A318', 300, 55, 'Airbus 324', 9);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(3400, 'A318', 300, 55, 'Airbus 325', 9);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(3500, 'A318', 300, 55, 'Airbus 326', 9);
INSERT INTO aircraft(id, code, nrEconomyClassSeats, nrFirstClassSeats, name, airlineFK_id) VALUES(3600, 'A318', 300, 55, 'Airbus 327', 9);

INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(10, 'HMJ', '(HMJ) Khmelnitskiy Airport, UA', 'HMJ', 'UA', 'UKRAINE',  'Central Asia', '(HMJ) Khmelnitskiy Airport, UA');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(20, 'PPB', 'Presidente Prudente', 'PPB', 'BR', 'BRAZIL',  'South-America', 'A De Barros');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(30, 'AAH', 'Aachen', 'AAH', 'DE', 'GERMANY',  'Europe', 'Aachen Merzbruck Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(40, 'AAL', 'Aalborg', 'AAL', 'DK', 'DENMARK',  'Europe', 'Aalborg Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(50, 'AAR', 'Aarhus', 'ZID', 'DK', 'DENMARK',  'Europe', 'Aarhus Bus Service');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(60, 'HMJ', '(HMJ) Khmelnitskiy Airport, UA', 'HMJ', 'UA', 'UKRAINE',  'Central Asia', '(HMJ) Khmelnitskiy Airport, UA');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(70, 'PPB', 'Presidente Prudente', 'PPB', 'BR', 'BRAZIL',  'South-America', 'A De Barros');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(80, 'AAH', 'Aachen', 'AAH', 'DE', 'GERMANY',  'Europe', 'Aachen Merzbruck Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(90, 'AAL', 'Aalborg', 'AAL', 'DK', 'DENMARK',  'Europe', 'Aalborg Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(100, 'AAR', 'Aarhus', 'ZID', 'DK', 'DENMARK',  'Europe', 'Aarhus Bus Service');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(110, 'JEG', 'Aasiaat', 'JEG', 'GL', 'GREENLAND',  'Europe', 'Aasiaat Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(120, 'DIR', 'Dire Dawa', 'DIR', 'ET', 'ETHIOPIA',  'Afrika', 'Aba Tenna D Yilma Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(130, 'ABD', 'Abadan', 'ABD', 'IR', 'IRAN',  'Middle East', 'Abadan Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(140, 'ABA', 'Abakan', 'ABA', 'RU', 'RUSSIA',  'Central Asia', 'Abakan Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(150, 'YXX', 'Abbotsford', 'YXX', 'CA', 'CANADA',  'North America', 'Abbotsford Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(160, 'ABR', 'Aberdeen', 'ABR', 'US', 'UNITED STATES',  'North America', 'Aberdeen Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(170, 'ABZ', 'Aberdeen', 'ZXA', 'GB', 'UNITED KINGDOM',  'Europe', 'Aberdeen ScotRail Station');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(180, 'AHB', 'Abha', 'AHB', 'SA', 'SAUDI ARABIA',  'Middle East', 'Abha Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(190, 'ABI', 'Abilene', 'ABI', 'US', 'UNITED STATES',  'North America', 'Abilene Municipal Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(200, 'AUH', 'Abu Dhabi', 'ZVJ', 'AE', 'UNITED ARAB EMIRATES',  'Middle East', 'Abu Dhabi-bus Station');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(210, 'ABS', 'Abu Simbel', 'ABS', 'EG', 'EGYPT',  'Afrika', 'Abu Simbel Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(220, 'ABV', 'Abuja', 'ABV', 'NG', 'NIGERIA',  'Afrika', 'Abuja International');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(230, 'ACS', 'Achinsk Airport', 'ACS', 'RU', 'RUSSIA',  'Central Asia', 'Achinsk Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(240, 'SRG', 'Semarang', 'SRG', 'ID', 'INDONESIA',  'Asia', 'Achmad Uani Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(250, 'ADT', 'Ada OK', 'ADT', 'US', 'UNITED STATES',  'North America', 'Ada Municipal Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(260, 'ADK', 'Adak Island', 'ADK', 'US', 'UNITED STATES',  'North America', 'Adak Island Ns');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(270, 'ADA', 'Adana', 'ADA', 'TR', 'TURKEY',  'Middle East', 'Adana Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(280, 'EKX', 'Elizabethtown', 'EKX', 'US', 'UNITED STATES',  'North America', 'Addington Field');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(290, 'DFW', 'Dallas', 'ADS', 'US', 'UNITED STATES',  'North America', 'Addison Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(300, 'ADL', 'Adelaide', 'ADL', 'AU', 'AUSTRALIA',  'Oceania', 'Adelaide Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(310, 'SOC', 'Solo', 'SOC', 'ID', 'INDONESIA',  'Asia', 'Adi Sumarno Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(320, 'SLK', 'Saranac Lake', 'SLK', 'US', 'UNITED STATES',  'North America', 'Adirondack Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(330, 'JOG', 'Yogyakarta', 'JOG', 'ID', 'INDONESIA',  'Asia', 'Adisutjipto Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(340, 'ADF', 'Adiyaman', 'ADF', 'TR', 'TURKEY',  'Middle East', 'Adiyaman Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(350, 'IZM', 'Izmir', 'ADB', 'TR', 'TURKEY',  'Middle East', 'Adnan Menderes Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(360, 'FLW', 'Santa Cruz Flores', 'FLW', 'PT', 'PORTUGAL',  'Europe', 'Aerodromo Das Flores');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(370, 'MAH', 'Menorca', 'MAH', 'ES', 'SPAIN',  'Europe', 'Aerop De Menorca');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(380, 'LOH', 'Loja', 'LOH', 'EC', 'ECUADOR',  'South-America', 'Aeropuerto Camilo Enriquez');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(390, 'LPA', 'Gran Canaria', 'LPA', 'ES', 'SPAIN',  'Europe', 'Aeropuerto De Gran Canaria');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(400, 'MTY', 'Monterrey', 'NTR', 'MX', 'MEXICO',  'Central America', 'Aeropuerto Del Norte');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(410, 'LAP', 'La Paz', 'LAP', 'MX', 'MEXICO',  'Central America', 'Aeropuerto Gen Marquez De Leon');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(420, 'CZM', 'Cozumel', 'CZM', 'MX', 'MEXICO',  'Central America', 'Aeropuerto International De Cozumel');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(430, 'SCI', 'San Crystobal', 'SCI', 'VE', 'VENEZUELA',  'South-America', 'Aeropuerto Santo Domingo');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(440, 'CWB', 'Curitiba', 'CWB', 'BR', 'BRAZIL',  'South-America', 'Afonso Pena Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(450, 'AFY', 'Afyon Airport', 'AFY', 'TR', 'TURKEY',  'Middle East', 'Afyon Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(460, 'AGA', 'Agadir', 'AGA', 'MA', 'MOROCCO',  'Afrika', 'Agadir Almassira Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(470, 'LUG', 'Lugano', 'LUG', 'CH', 'SWITZERLAND',  'Europe', 'Agno Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(480, 'RJL', 'Logrono', 'RJL', 'ES', 'SPAIN',  'Europe', 'Agoncillo Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(490, 'AJI', 'Agri', 'AJI', 'TR', 'TURKEY',  'Middle East', 'Agri Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(500, 'AGQ', 'Agrinion', 'AGQ', 'GR', 'GREECE',  'Europe', 'Agrinion Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(510, 'AGU', 'Aguascalientes', 'AGU', 'MX', 'MEXICO',  'Central America', 'Aguascalientes Municipal Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(520, 'AIK', 'Aiken', 'AIK', 'US', 'UNITED STATES',  'North America', 'Aiken Municipal Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(530, 'CZL', 'Constantine', 'CZL', 'DZ', 'ALGERIA',  'Afrika', 'Ain El Bey Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(540, 'ANW', 'Ainsworth', 'ANW', 'US', 'UNITED STATES',  'North America', 'Ainsworth Minicipal Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(550, 'UWE', 'Wiesbaden', 'WIE', 'DE', 'GERMANY',  'Europe', 'Air Base');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(560, 'SEF', 'Sebring', 'SEF', 'US', 'UNITED STATES',  'North America', 'Air Terminal Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(570, 'ROR', 'Koror', 'ROR', 'PW', 'PALAU',  '', 'Airai Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(580, 'BRM', 'Barquisimeto', 'BRM', 'VE', 'VENEZUELA',  'South-America', 'Airport Barquisimeto');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(590, 'OXB', 'Bissau', 'OXB', 'GW', 'GUINEA-BISSAU',  '', 'Airport Osvaldo Viera');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(600, 'AIT', 'Aitutaki', 'AIT', 'CK', 'COOK ISLANDS',  '', 'Aitutaki Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(610, 'QXB', 'Aix En Provence', 'QXB', 'FR', 'FRANCE',  'Europe', 'Aix en Provence Rail Station');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(620, 'AXT', 'Akita', 'AXT', 'JP', 'JAPAN',  'Asia', 'Akita Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(630, 'CAK', 'Akron', 'CAK', 'US', 'UNITED STATES',  'North America', 'Akron Canton Regional Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(640, 'AKU', 'Aksu', 'AKU', 'CN', 'CHINA',  'Asia', 'Aksu Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(650, 'SCO', 'Aktau', 'SCO', 'KZ', 'KAZAKHSTAN',  '', 'Aktau Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(660, 'PVK', 'Preveza', 'PVK', 'GR', 'GREECE',  'Europe', 'Aktion Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(670, 'AKV', 'Akulivik', 'AKV', 'CA', 'CANADA',  'North America', 'Akulivik Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(680, 'AEY', 'Akureyri', 'AEY', 'IS', 'ICELAND',  'Europe', 'Akureyri');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(690, 'AAN', 'Al Ain', 'AAN', 'AE', 'UNITED ARAB EMIRATES',  'Middle East', 'Al Ain Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(700, 'ABT', 'Al Baha', 'ABT', 'SA', 'SAUDI ARABIA',  'Middle East', 'Al Aqiq');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(710, 'AAY', 'Al Ghaydah', 'AAY', 'YE', 'YEMEN',  'Afrika', 'Al Ghaydah Airport');
INSERT INTO airport(id, cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values(720, 'DEZ', 'Deirezzor', 'DEZ', 'SY', 'SYRIA',  'Middle East', 'Al Jafrah Airport');

INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1000, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1100, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1200, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1300, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1400, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1500, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1600, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1700, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1800, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1900, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2000, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2100, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2200, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2300, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2400, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2500, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2600, 10);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2700, 20);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1000, 20);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1100, 20);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1200, 20);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1300, 20);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1400, 20);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1500, 20);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1600, 20);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1700, 20);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1800, 20);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1900, 20);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2000, 30);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2100, 30);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2200, 30);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2300, 30);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2400, 30);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2500, 40);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2600, 40);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2700, 40);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1000, 40);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1100, 50);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1200, 50);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1300, 50);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1400, 50);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1500, 60);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1600, 60);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1700, 70);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1800, 80);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1800, 90);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(1900, 100);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2000, 110);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2100, 120);
INSERT INTO airline_airport(AirlineEntity_id, airportFK_id) VALUES(2200, 130);


 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 10, FALSE, 200.5, 2, 10); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 20, FALSE, 100.5, 1, 10); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 30, FALSE, 200, 2, 10); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 40, FALSE, 300.5, 3, 10); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 50, FALSE, 100.5, 1, 10); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 60, FALSE, 100.5, 1, 10); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 70, FALSE, 100.5, 1, 20); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 80, FALSE, 100.5, 1, 40); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 90, TRUE, 100.5, 1, 30); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 100, FALSE, 400.5, 4, 30); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 110, FALSE, 400.5, 4, 30); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 120, FALSE, 400.5, 4, 30); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 130, TRUE, 400.5, 4, 30); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 140, FALSE, 400.5, 4, 50); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 150, FALSE, 400.5, 4, 50); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 160, FALSE, 400.5, 4, 50); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 170, TRUE, 400.5, 4, 50); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 180, FALSE, 400.5, 4, 50); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 190, FALSE, 100.5, 1, 50); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 200, FALSE, 200.5, 2, 60); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 210, FALSE, 400.5, 1, 60); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 220, FALSE, 300.5, 3, 60); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 230, TRUE, 400.5, 1, 60); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 240, FALSE, 500.5, 5, 60); 
 INSERT INTO bookedflight(id, cancelled, pricePaid, seatsBooked, sheduleFK_id) VALUES( 250, FALSE, 100.5, 8, 60); 

 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 10); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 20); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 30); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 40); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 50); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 60); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 70); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 80); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 90); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 100); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 110); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 120); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 130); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 140); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 150); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 160); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 170); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 180); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 190); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 200); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 210); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 220); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 230); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 240); 
 INSERT INTO bookedflight_user(id, BookedflightEntity_id, personFK_id) VALUES( 10, 250); 
 
 
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(10, 43455,0097222222, '43385', 250, 43454,9583333333, 10,  10, 100, 100);
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(20, 43456,0097222222, '43386', 300, 43455,9583333333, 4,  20, 200, 500);
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(30, 43457,0097222222, '43387', 250, 43456,9583333333, 100,  20, 600, 400);
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(40, 43458,0097222222, '43388', 300, 43457,9583333333, 4,  30, 400, 200);
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(50, 43459,0097222222, '43389', 250, 43458,9583333333, 200,  50, 500, 100);
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(60, 43460,0097222222, '43390', 240, 43459,9583333333, 10,  40, 400, 100);
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(70, 43461,0097222222, '43391', 150, 43460,9583333333, 0,  10, 200, 100);
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(80, 43462,0097222222, '43392', 60, 43461,9583333333, 1,  20, 200, 300);

 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 10, 5, 2, 1000, 10); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 20, 6, 3, 1000, 10); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 30, 7, 5, 1000, 10); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 40, 8, 6, 1000, 20); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 50, 10, 9, 1000, 20); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 60, 2, 2, 1100, 20); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 70, 3, 3, 1100, 20); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 80, 4, 5, 1100, 20); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 90, 5, 6, 1100, 20); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 100, 6, 9, 1100, 20); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 110, 8, 6, 1200, 20); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 120, 10, 9, 1200, 30); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 130, 2, 2, 1300, 30); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 140, 3, 3, 1300, 30); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 150, 4, 5, 1300, 30); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 160, 5, 6, 1300, 30); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 170, 5, 6, 1400, 30); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 180, 1, 2, 1500, 30); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 190, 2, 3, 1500, 30); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 200, 3, 5, 1500, 50); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 210, 4, 6, 1500, 50); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 220, 2, 3, 1600, 50); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 230, 1, 2, 1700, 50); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 240, 2, 3, 1700, 50); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 250, 3, 5, 1700, 60); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 260, 3, 5, 1800, 60); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 270, 4, 6, 1800, 60); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 280, 1, 2, 1800, 60); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 290, 2, 3, 1900, 60); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 300, 4, 5, 1900, 60); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 310, 5, 6, 1900, 70); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 320, 1, 2, 2000, 70); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 330, 2, 3, 2000, 70); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 340, 4, 5, 2000, 70); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 350, 5, 6, 2000, 70); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 360, 1, 2, 2100, 70); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 370, 2, 3, 2100, 70); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 380, 3, 4, 2100, 70); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 390, 1, 2, 2200, 70); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 400, 2, 3, 2200, 80); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 410, 4, 5, 2300, 80); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 420, 4, 5, 2400, 80); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 430, 2, 5, 2500, 80); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 440, 1, 2, 2600, 80); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 450, 2, 3, 2600, 90); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 460, 3, 4, 2600, 90); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 470, 4, 5, 2600, 90); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 480, 5, 6, 2600, 90); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 490, 1, 2, 2700, 90); 										
 INSERT INTO discount(id, discountPercentage, minNumOfSeatsReserved, airlineFK_id, sheduleFK_id) VALUES( 500, 2, 3, 2700, 90); 										

INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(10, 43455,0097222222, '43385', 250, 43454,9583333333, 10,  10, 100, 100);
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(20, 43456,0097222222, '43386', 300, 43455,9583333333, 4,  20, 200, 500);
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(30, 43457,0097222222, '43387', 250, 43456,9583333333, 100,  20, 600, 400);
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(40, 43458,0097222222, '43388', 300, 43457,9583333333, 4,  30, 400, 200);
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(50, 43459,0097222222, '43389', 250, 43458,9583333333, 200,  50, 500, 100);
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(60, 43460,0097222222, '43390', 240, 43459,9583333333, 10,  40, 400, 100);
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(70, 43461,0097222222, '43391', 150, 43460,9583333333, 0,  10, 200, 100);
INSERT INTO shedule(id,  arrivalTime, date, defaultPrice, departureTime, remainingSeats, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(80, 43462,0097222222, '43392', 60, 43461,9583333333, 1,  20, 200, 300);


