INSERT INTO airline(name, code) VALUES('KLM', 'KLM');
INSERT INTO airline(name, code) VALUES('SWISS', 'SW');
INSERT INTO airline(name, code) VALUES('Air Belgium', 'AB');
INSERT INTO airline(name, code) VALUES('ASL Airlines Belgium', 'ASL');
INSERT INTO airline(name, code) VALUES('Brussels Airlines N.V.', 'BA');
INSERT INTO airline(name, code) VALUES('TUI Airlines Belgium NV', 'TUI');
INSERT INTO airline(name, code) VALUES('Vueling', 'Vue');
INSERT INTO airline(name, code) VALUES('Air Hollandia B.V.', 'AH');
INSERT INTO airline(name, code) VALUES('Ryanair', 'RYN');
INSERT INTO airline(name, code) VALUES('Lufthansa', 'LU');
INSERT INTO airline(name, code) VALUES('American Airlines', 'AA');
INSERT INTO airline(name, code) VALUES('ToGethAir Employees', 'TGA');

INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('Cessna 510', 0, 0, 4, 'Cessna 510 Mustang', 1);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('Cessna C525', 0, 0, 6, 'Cessna C525 Citation CJ2', 2);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 100, 55, 0, 'Airbus 319', 3);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 110, 55, 0, 'Airbus 320', 4);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 120, 55, 0, 'Airbus 321', 5);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 130, 55, 0, 'Airbus 322', 6);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 140, 55, 0, 'Airbus 323', 7);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 150, 55, 0, 'Airbus 324', 8);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 160, 55, 0, 'Airbus 325', 9);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 170, 55, 0, 'Airbus 326', 10);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A321', 250, 30, 8, 'Airbus A321-100/200', 11);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A321', 250, 30, 8, 'Airbus A321-100/200', 1);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A321', 250, 30, 8, 'Airbus A321-100/200', 2);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A321', 250, 30, 8, 'Airbus A321-100/200', 3);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A330', 290, 55, 0, 'Airbus A330 ', 4);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 5);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 100, 55, 0, 'Airbus 319', 3);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 110, 55, 0, 'Airbus 320', 4);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 120, 55, 0, 'Airbus 321', 5);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 130, 55, 0, 'Airbus 322', 6);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 140, 55, 0, 'Airbus 323', 7);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 150, 55, 0, 'Airbus 324', 8);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 160, 55, 0, 'Airbus 325', 9);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 170, 55, 0, 'Airbus 326', 10);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 100, 55, 0, 'Airbus 319', 10);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 110, 55, 0, 'Airbus 320', 9);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 120, 55, 0, 'Airbus 321', 8);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 130, 55, 0, 'Airbus 322', 7);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 140, 55, 0, 'Airbus 323', 6);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 150, 55, 0, 'Airbus 324', 5);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 160, 55, 0, 'Airbus 325', 4);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 170, 55, 0, 'Airbus 326', 3);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 2);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 100, 55, 0, 'Airbus 319', 1);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A330', 290, 55, 0, 'Airbus A330 ', 1);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A330', 290, 55, 0, 'Airbus A330 ', 2);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 3);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 4);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 5);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 6);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A330', 290, 55, 0, 'Airbus A330 ', 7);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 8);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 9);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 10);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 11);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 10);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 9);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 8);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 7);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 6);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 5);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 4);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 3);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 2);
INSERT INTO aircraft(code, economyClassSeats, businessClassSeats, firstClassSeats, name, airlineFK_id) VALUES('A318', 300, 55, 0, 'Airbus 319', 1);

INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('CHA', 'Chalerloi', 'CRL', 'BE', 'BELGIUM', 'Europe',  'Brussels South Charleroi Arpt');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('OST', 'Ostende', 'OST',   'BE', 'BELGIUM', 'Europe',  'Ostend Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('ANT', 'Antwerp',  'ZYZ', 'BE', 'BELGIUM', 'Europe',   'Antwerp Berchem Rail Station');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('BRU', 'Brussels', 'BRU',  'BE', 'BELGIUM', 'Europe','Brussels National Arpt');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('LPA', 'Gran Canaria', 'LPA', 'ES', 'SPAIN',  'Europe', 'Aeropuerto De Gran Canaria');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('PAR', 'Paris', 'CDG', 'FR', 'FRANCE', 'Europe', 'Charles De Gaulle Intl Arpt');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('BML', 'Berlin', 'BER', 'DE',  'BELGIUM', 'Europe', 'Berlin Arpt');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('LON', 'London', 'LHR', 'GB', 'UNITED KINGDOM', 'Europe', 'Heathrow');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('HMJ', '(HMJ) Khmelnitskiy Airport, UA', 'HMJ', 'UA', 'UKRAINE',  'Central Asia', '(HMJ) Khmelnitskiy Airport, UA');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('PPB', 'Presidente Prudente', 'PPB', 'BR', 'BRAZIL',  'South-America', 'A De Barros');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('AAH', 'Aachen', 'AAH', 'DE', 'GERMANY',  'Europe', 'Aachen Merzbruck Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('AAL', 'Aalborg', 'AAL', 'DK', 'DENMARK',  'Europe', 'Aalborg Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('AAR', 'Aarhus', 'ZID', 'DK', 'DENMARK',  'Europe', 'Aarhus Bus Service');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('JEG', 'Aasiaat', 'JEG', 'GL', 'GREENLAND',  'Europe', 'Aasiaat Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('DIR', 'Dire Dawa', 'DIR', 'ET', 'ETHIOPIA',  'Africa', 'Aba Tenna D Yilma Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('ABD', 'Abadan', 'ABD', 'IR', 'IRAN',  'Middle East', 'Abadan Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('ABA', 'Abakan', 'ABA', 'RU', 'RUSSIA',  'Central Asia', 'Abakan Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('YXX', 'Abbotsford', 'YXX', 'CA', 'CANADA',  'North America', 'Abbotsford Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('ABR', 'Aberdeen', 'ABR', 'US', 'UNITED STATES',  'North America', 'Aberdeen Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('AHB', 'Abha', 'AHB', 'SA', 'SAUDI ARABIA',  'Middle East', 'Abha Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('ABI', 'Abilene', 'ABI', 'US', 'UNITED STATES',  'North America', 'Abilene Municipal Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('AUH', 'Abu Dhabi', 'ZVJ', 'AE', 'UNITED ARAB EMIRATES',  'Middle East', 'Abu Dhabi-bus Station');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('ABS', 'Abu Simbel', 'ABS', 'EG', 'EGYPT',  'Africa', 'Abu Simbel Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('ABV', 'Abuja', 'ABV', 'NG', 'NIGERIA',  'Africa', 'Abuja International');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('ACS', 'Achinsk Airport', 'ACS', 'RU', 'RUSSIA',  'Central Asia', 'Achinsk Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('SRG', 'Semarang', 'SRG', 'ID', 'INDONESIA',  'Asia', 'Achmad Uani Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('ADT', 'Ada OK', 'ADT', 'US', 'UNITED STATES',  'North America', 'Ada Municipal Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('ADK', 'Adak Island', 'ADK', 'US', 'UNITED STATES',  'North America', 'Adak Island Ns');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('ADA', 'Adana', 'ADA', 'TR', 'TURKEY',  'Middle East', 'Adana Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('EKX', 'Elizabethtown', 'EKX', 'US', 'UNITED STATES',  'North America', 'Addington Field');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('DFW', 'Dallas', 'ADS', 'US', 'UNITED STATES',  'North America', 'Addison Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('ADL', 'Adelaide', 'ADL', 'AU', 'AUSTRALIA',  'Oceania', 'Adelaide Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('SOC', 'Solo', 'SOC', 'ID', 'INDONESIA',  'Asia', 'Adi Sumarno Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('SLK', 'Saranac Lake', 'SLK', 'US', 'UNITED STATES',  'North America', 'Adirondack Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('JOG', 'Yogyakarta', 'JOG', 'ID', 'INDONESIA',  'Asia', 'Adisutjipto Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('ADF', 'Adiyaman', 'ADF', 'TR', 'TURKEY',  'Middle East', 'Adiyaman Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('IZM', 'Izmir', 'ADB', 'TR', 'TURKEY',  'Middle East', 'Adnan Menderes Airport');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('FLW', 'Santa Cruz Flores', 'FLW', 'PT', 'PORTUGAL',  'Europe', 'Aerodromo Das Flores');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('MAH', 'Menorca', 'MAH', 'ES', 'SPAIN',  'Europe', 'Aerop De Menorca');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName) values('LOH', 'Loja', 'LOH', 'EC', 'ECUADOR',  'South-America', 'Aeropuerto Camilo Enriquez');
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName, continent) values('Nor', 'North America', 'Nor', 'No', 'North America',  'North America', 'North America', true);
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName, continent) values('Asi', 'Asia', 'Asi', 'As', 'Asia',  'Asia', 'Asia', true);
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName, continent) values('Cen', 'Central Asia', 'Cen', 'Ce', 'Central Asia',  'Central Asia', 'Central Asia', true);
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName, continent) values('Mid', 'Middle East', 'Mid', 'Mi', 'Middle East',  'Middle East', 'Middle East', true);
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName, continent) values('Eur', 'Europe', 'Eur', 'Eu', 'Europe',  'Europe', 'Europe', true);
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName, continent) values('Sou', 'South-America', 'Sou', 'So', 'South-America',  'South-America', 'South-America', true);
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName, continent) values('Afr', 'Africa', 'Afr', 'Af', 'Africa',  'Africa', 'Africa', true);
INSERT INTO airport(cityCode, cityName, airportCode, countryCode, countryName, globalRegionLocation, airportName, continent) values('Oce', 'Oceania', 'Oce', 'Oc', 'Oceania',  'Oceania', 'Oceania', true);

INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 1);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 1);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 1);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 1);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 1);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 1);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 1);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 1);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(9, 1);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 2);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 2);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 2);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 2);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 2);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 2);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 2);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 2);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(9, 2);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 3);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 3);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 3);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 3);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 3);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 3);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 3);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 3);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(9, 3);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 4);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 4);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 4);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 4);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 4);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 4);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 4);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 4);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(9, 4);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 5);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 5);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 5);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 5);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 5);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 5);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 5);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 5);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(9, 5);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 6);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 6);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 6);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 6);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 6);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 6);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 6);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 6);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(9, 6);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 7);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 7);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 7);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 7);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 7);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 7);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 7);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 7);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(9, 7);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 8);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 8);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 8);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 8);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 8);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 8);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 8);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 8);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(9, 8);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 9);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 9);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 9);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 9);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 9);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 9);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 9);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 9);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(9, 9);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 10);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 10);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 10);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 10);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 10);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 10);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 10);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 10);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 11);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 11);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 11);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 11);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 11);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 11);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 11);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 11);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 12);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 12);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 12);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 12);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 12);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 12);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 12);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 12);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(9, 12);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 13);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 13);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 13);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 13);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 13);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 13);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 13);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 13);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(9, 13);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 14);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 14);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 14);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 14);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 14);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 14);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 14);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 14);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(9, 14);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 15);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 15);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 15);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 15);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 15);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 15);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 15);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 15);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(9, 15);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 16);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 16);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 16);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 16);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 16);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 16);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 16);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 16);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 17);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 17);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 17);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 17);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 17);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 17);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 17);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 17);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 18);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 18);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 18);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 18);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 18);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 18);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 18);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 18);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 19);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 19);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 19);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 19);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 19);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 19);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 19);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 19);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 20);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 20);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 20);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 20);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 20);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 20);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 20);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 20);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 21);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 21);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 21);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 21);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 21);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 21);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 21);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 21);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(9, 21);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(1, 22);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(2, 22);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(3, 22);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(4, 22);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(5, 22);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(6, 22);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(7, 22);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(8, 22);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(10, 1);
INSERT INTO airline_airport(Airline_FK, airport_FK) VALUES(11, 1);

insert into login(email, password, role) values ('timmerel@gmail.com', 'paswoord', 0);
insert into user(category, firstName, lastName, country, mobilePhone, birthDate, version, login_id, airline_id) values ('C', 'Tom', 'Merel', 'Belgium', '048553322', '1964-12-28', 0.1, 1, 12);

insert into login(email, password, role) values ('geraldBien@gmail.com', 'paswoord', 2);
insert into user(category, firstName, lastName, country, mobilePhone, birthDate, version, login_id, airline_id) values ('E','Gerald', 'Bien', 'Belgium', '048553322', '1964-12-28', 0.1, 2, null);

insert into login(email, password, role) values ('BartBier@gmail.com', 'paswoord', 1);
insert into user(category, firstName, lastName, country, mobilePhone, birthDate, version, login_id, airline_id) values ('P', 'Bart', 'Bier', 'Belgium', '048553322', '1964-12-28', 0.1, 3, 1);

insert into login(email, password, role) values ('MerelPeeters@gmail.com', 'paswoord', 1);
insert into user(category, firstName, lastName, country, mobilePhone, birthDate, version, login_id, airline_id) values ('P', 'Merel', 'Peeters', 'Belgium', '048553322', '1964-12-28', 0.1, 4, 5);

insert into login(email, password, role) values ('mallerakker@gmail.com', 'paswoord', 2);
insert into user(category, firstName, lastName, country, mobilePhone, birthDate, version, login_id, airline_id) values ('E','Koen', 'De Bakker', 'Belgium', '0458968468', '1964-09-28', 0.1, 5, null);


INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 20, 1539874850, 250, 5,0, 3, 1, 3);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 16, 1539874800, 300, 5,0, 4, 2, 5);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 44, 1539874800, 250, 5,0, 4, 6, 4);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 60, 1539874850, 300, 5,0, 5, 4, 2);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 87, 1539874800, 250, 5,0, 7, 5, 1);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 149,1539874800, 240, 5,0, 6, 4, 1);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 159,1539874800, 150, 5,0, 3, 2, 1);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 165,1539874800, 60,  5,0, 4, 2, 3);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 35, 1539889400, 250, 5,0, 3, 1, 5);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 10, 1539889500, 300, 5,0, 4, 2, 5);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 44, 1539889600, 250, 5,0, 4, 6, 4);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 60, 1539889100, 300, 5,0, 5, 4, 2);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 86, 1539889000, 250, 5,0, 7, 5, 1);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 150,1539889200, 240, 5,0, 6, 4, 1);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 160,1539889000, 150, 5,0, 3, 2, 1);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 165,1539889200, 60,  15,0, 4, 2, 3);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 23, 1539874600, 250, 15,0, 3, 3, 1);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 19, 1539874700, 300, 15,0, 4, 5, 2);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 44, 1539874800, 250, 15,0, 4, 4, 6);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 61, 1539874900, 300, 15,0, 5, 2, 4);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 82, 1539874650, 250, 15,0, 7, 1, 5);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 150,1539874590, 240, 15,0, 6, 1, 4);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 160,1539874720, 150, 15,0, 3, 1, 2);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539864000,'18/10/2018', 165,1539874800, 60,  15,0, 4, 3, 2);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 22, 1539889200, 250, 15,0, 3, 5, 1);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 18, 1539889300, 300, 15,0, 4, 5, 2);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 44, 1539889200, 250, 15,0, 4, 4, 6);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 60, 1539889500, 300, 15,0, 5, 2, 4);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 87, 1539889250, 250, 15,0, 7, 1, 5);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 150,1539889220, 240, 15,0, 6, 1, 4);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 80, 1539889200, 0, 0, 4, 1, 1, 2);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'19/10/2018', 87, 1539889240, 0, 0, 6, 2, 2, 1);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539878400,'18/10/2018', 80, 1539889230, 0, 0, 4, 1, 1, 2);
INSERT INTO shedule(arrivalTime, date, defaultPrice, departureTime, remainingSeatsEconomy, remainingSeatsBusiness, remainingSeatsFirst, aircraftFK_id, arrivalAirtportFK_id, departureAirtportFK_id) values(1539889200,'18/10/2018', 87, 1539874820, 0, 0, 6, 2, 2, 1);


INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PENDING', FALSE, 200.5, 2, 1, 1);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', FALSE, 100.5, 1, 1, 2);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', FALSE, 200, 2, 1, 3);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', FALSE, 300.5, 3, 1, 4);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', FALSE, 100.5, 1, 1, 5);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', FALSE, 100.5, 1, 2, 1);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', FALSE, 100.5, 1, 4, 1);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', TRUE, 100.5, 1, 3, 2);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', FALSE, 400.5, 4, 3, 1);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', FALSE, 400.5, 4, 3, 2);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', FALSE, 400.5, 4, 3, 3);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', TRUE, 400.5, 4, 3, 4);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', FALSE, 400.5, 4, 5, 2);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', FALSE, 400.5, 4, 5, 3);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', FALSE, 400.5, 4, 5, 4);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Creditcard', 'PAID', TRUE, 400.5, 4, 5, 5);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Endorsement', 'PENDING', FALSE, 100.5, 1, 5,1);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Endorsement', 'PENDING', FALSE, 200.5, 2, 6, 1);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Endorsement', 'PENDING', FALSE, 400.5, 1, 6, 2);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Endorsement', 'PENDING', FALSE, 300.5, 3, 6, 3);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Endorsement', 'PENDING', TRUE, 400.5, 1, 6, 4);
INSERT INTO bookedflight(payMethod, paymentStatus, cancelled, pricePaid, seatsBooked, sheduleFK_id, userFK_id) VALUES('Endorsement', 'PENDING', FALSE, 500.5, 5, 6, 5);

INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 5, 2, 1, 10);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 6, 3, 2, 10);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 7, 5, 1, 10);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 8, 6, 1, 12);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 10, 9, 1,12);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 2, 2, 2, 12);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 3, 3, 2, 12);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 4, 5, 2, 12);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 5, 6, 2, 12);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 6, 9, 2, 12);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 8, 6, 3, 12);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 10, 9, 2,16);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 2, 2, 4, 16);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 3, 3, 4, 16);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 4, 5, 4, 16);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 5, 6, 4, 16);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 5, 6, 5, 16);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 1, 2, 5, 16);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 2, 3, 5, 16);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 3, 5, 5, 18);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 4, 6, 5, 18);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 2, 3, 6, 18);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 1, 2, 7, 18);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 2, 3, 7, 20);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 3, 5, 7, 22);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 3, 5, 8, 22);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 4, 6, 8, 22);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 1, 2, 8, 22);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 2, 3, 9, 22);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 4, 5, 9, 22);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 5, 6, 9, 24);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 1, 2, 10,24);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 2, 3, 10,24);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 4, 5, 10,24);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 5, 6, 10,24);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 1, 2, 1, 24);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 2, 3, 1, 24);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 3, 4, 1, 24);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 1, 2, 12, 24);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 2, 3, 12, 25);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 4, 5, 13, 25);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 4, 5, 14, 25);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 2, 5, 15, 25);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 1, 2, 16, 25);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 2, 3, 16, 25);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 3, 4, 16, 30);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 4, 5, 16, 30);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 5, 6, 16, 30);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 1, 2, 17, 30);
INSERT INTO discount(minNumOfSeatsReserved, airlineFK_id, sheduleFK_id, discountPercentage) VALUES( 2, 3, 17, 30);